on:
  push:
    branches: [master]
  schedule:
    - cron: '0 12 1 * *'  # Monthly each 1st at 12:00
jobs:
  reenable:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: python3 reenable.py 2>/dev/null
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
